import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name_ar: 'دراجة هيلكس الرياضية الكربونية',
    name_en: 'Helix Carbon F-70 Sport Bike',
    name_fr: 'Vélo de Sport Helix Carbon F-70',
    description_ar: 'دراجة هوائية رياضية فائقة الخفة مصنوعة من ألياف الكربون، مصممة للمسافات الطويلة والسباقات الجبلية مع نظام مكابح هيدروليكي فائق الاستجابة.',
    description_en: 'An ultra-lightweight carbon fiber sports bicycle designed for long-distance cruising and rugged mountain racing, equipped with responsive hydraulic disc brakes.',
    description_fr: 'Un vélo de sport ultra-léger en fibre de carbone conçu pour le cyclisme de longue distance et le VTT, équipé de freins à disque hydrauliques haute performance.',
    features_ar: 'هيكل كربوني 100%, 22 سرعة شيمانو, مكابح هيدروليكية ذكية, مقعد طبي مضاد للاهتزاز',
    features_en: '100% Carbon fiber frame, 22-speed Shimano gears, Intelligent hydraulic brakes, Ergonomic anti-shock seat',
    features_fr: 'Cadre 100% fibre de carbone, Transmission Shimano 22 vitesses, Freins hydrauliques, Selle ergonomique anti-choc',
    tag_ar: 'مميز',
    tag_en: 'Featured',
    tag_fr: 'Populaire',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80',
    additional_images: [
      'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1541614101331-1a5a3a194e92?auto=format&fit=crop&w=800&q=80'
    ],
    price: 1290,
    stock: 12,
    category: 'bikes',
    rating_sum: 24,
    rating_count: 5,
    is_featured: true
  },
  {
    id: 'prod-2',
    name_ar: 'سيارة إي-رودستر الكهربائية المصغرة',
    name_en: 'Cyber E-Roadster Mini Cruiser',
    name_fr: 'Mini Cruiser Cyber E-Roadster',
    description_ar: 'أحدث سيارة كهربائية فائقة لرجال العصر المستقبلي، تدعم نظام شحن فائق السرعة، ومقاعد جلدية فاخرة بنظام تحكم آلي مبتكر.',
    description_en: 'A gorgeous electric mini convertible roadster with dual-motor configurations, autonomous parking assist, and elegant vegan leather interior.',
    description_fr: 'Un magnifique mini roadster décapotable électrique avec configuration double moteur, stationnement autonome et intérieur élégant.',
    features_ar: 'بطارية ليثيوم 800 كم مداها, شاشات قيادة ثنائية, دفع رباعي ذكي, حماية مصفحة للأطفال',
    features_en: 'Battery life up to 800km range, Dual smart displays, AWD performance drive, Child-safe lock system',
    features_fr: 'Autonomie de batterie 800km, Double écran intelligent, Transmission intégrale, Verrouillage sécurisé enfant',
    tag_ar: 'الأكثر مبيعاً',
    tag_en: 'Best Seller',
    tag_fr: 'Meilleure Vente',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    additional_images: [
      'https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-3a3b142c6e3d?auto=format&fit=crop&w=800&q=80'
    ],
    price: 18500,
    stock: 5,
    category: 'cars',
    rating_sum: 49,
    rating_count: 10,
    is_featured: true
  },
  {
    id: 'prod-3',
    name_ar: 'ساعة كوانتوم الذكية إكس',
    name_en: 'Quantum Smartwatch Pro X',
    name_fr: 'Montre Intelligente Quantum X',
    description_ar: 'ساعة يد ذكية مقاومة للماء بنسبة 100٪ مع شاشة ريتنا فائقة السطوع، وقاريء مدمج لمعدلات نبضات القلب والضغط ونسب الأكسجين ومتبع نوم دقيق.',
    description_en: 'Luxurious water-resistant smartwatch with always-on Retina display, health vitals monitoring (HRV, SpO2, sleep tracking) and 14 days of battery cycle.',
    description_fr: 'Montre intelligente de luxe résistante à l\'eau avec écran Retina toujours allumé, surveillance médicale (FC, SpO2) et 14 jours d\'autonomie.',
    features_ar: 'شاشة AMOLED مقاس 1.9 إنش, تتبع صحي متقدم, نظام ملاحة GPS مدمج, هيكل تيتانيوم صلب',
    features_en: '1.9" Always-on AMOLED, Advanced health sensors, Precision GPS tracking, Titanium military-grade chassis',
    features_fr: 'Écran AMOLED 1.9", Capteurs de santé premium, Traceur GPS intégré, Boîtier en titane ultra-robuste',
    tag_ar: 'جديد',
    tag_en: 'New Arrival',
    tag_fr: 'Nouveau',
    image: 'https://images.unsplash.com/photo-1523275335684-87898b6baf30?auto=format&fit=crop&w=800&q=80',
    additional_images: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579586337278-8befd40fd17a?auto=format&fit=crop&w=800&q=80'
    ],
    price: 380,
    stock: 35,
    category: 'electronics',
    rating_sum: 18,
    rating_count: 4,
    is_featured: false
  },
  {
    id: 'prod-4',
    name_ar: 'سماعات هولو ساوند الهوائية',
    name_en: 'HoloSound Audio Over-Ear Max',
    name_fr: 'Casque Audio HoloSound Max',
    description_ar: 'سماعات لاسلكية عازلة تماماً للضجيج الخارجي توفر توزيعاً صوتياً سينمائياً ثلاثي الأبعاد مع بطارية ممتازة تدوم لأكثر من 40 ساعة متواصلة.',
    description_en: 'High-fidelity wire-free overhead headphones highlighting proactive Hybrid Noise Cancellation, 3D spatial surround flow, and customizable sound stages.',
    description_fr: 'Casque audio haute fidélité avec annulation de bruit active hybride, son spatial tridimensionnel et autonomie de 40 heures.',
    features_ar: 'إلغاء نويس هجين, صوت محيطي ثلاثي الأبعاد, 45 ساعة شحن كاملة, وسائد أذن ميموري فوم',
    features_en: 'Hybrid ANC, Spatial immersive sound, 45-hour playback, Memory foam ultra-comfort earmuffs',
    features_fr: 'ANC Hybride, Son spatial immersif, Autonomie de 45 heures, Coussinets ultra-confort en mémoire de forme',
    tag_ar: 'خصم 15%',
    tag_en: '15% Discount',
    tag_fr: '15% de Réduction',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    additional_images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-8032a568e944?auto=format&fit=crop&w=800&q=80'
    ],
    price: 249,
    stock: 25,
    category: 'electronics',
    rating_sum: 9,
    rating_count: 2,
    is_featured: false
  },
  {
    id: 'prod-5',
    name_ar: 'حقيبة السفر الجلدية رويال',
    name_en: 'Royal Sovereign Leather Duffle',
    name_fr: 'Sac de Voyage en Cuir Royal',
    description_ar: 'حقيبة سفر فاخرة مخيطة يدوياً بالكامل من أجود أنواع الجلود الإيطالية الطبيعية المقاومة للماء والأمطار، مناسبة لرحلات الطيران ورجال الأعمال.',
    description_en: 'An exquisite hand-stiched premium duffle travel bag manufactured with waterproof tanned Italian calfskin leather, incorporating deep utility pockets.',
    description_fr: 'Un sac de voyage raffiné cousu main en cuir de veau italien imperméable, idéal pour le week-end et les voyages d\'affaires.',
    features_ar: 'جلد طبيعي 100%, سحابات نحاسية مقاومة للصدأ, حزام عريض مبطن للاكتاف, سعة شاسعة',
    features_en: '100% Genuine Italian calfskin, Brass heavy-duty zippers, Ergonomic padded shoulder strap, High storage partition',
    features_fr: '100% Cuir italien véritable, Fermetures en laiton massif, Sangle d\'épaule rembourrée, Grand compartiment de stockage',
    tag_ar: 'ملكي',
    tag_en: 'Premium Selection',
    tag_fr: 'Choix Royal',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    additional_images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1553062407-77e8be22d86d?auto=format&fit=crop&w=800&q=80'
    ],
    price: 499,
    stock: 8,
    category: 'accessories',
    rating_sum: 15,
    rating_count: 3,
    is_featured: true
  },
  {
    id: 'prod-6',
    name_ar: 'خوذة نيو-كاربون الذكية للسباقات',
    name_en: 'NeoCarbon Smart Racing Helmet',
    name_fr: 'Casque Intelligent NeoCarbon',
    description_ar: 'خوذة حماية احترافية مدمجة بالدراجين مصنوعة من الكربون الصلب ومزودة بمكابح تواصل لاسلكية وبلوتوث وإضاءات إشارات LED خلفية تلقائية لرحلة ركوب آمنة.',
    description_en: 'A military-grade high durability carbon smart racing helmet with integrated Bluetooth communications, turn indicators, and shock-absorbent gel paddings.',
    description_fr: 'Casque de vélo intelligent en fibre de carbone équipé d\'intercom Bluetooth, clignotants LED automatiques et rembourrage gel anti-chocs.',
    features_ar: 'بلوتوث مدمج للاتصالات, نظام إشارات LED ذكي, مستشعر حوادث وطوارئ, حائزة على شهادات أمان عالمية',
    features_en: 'Integrated Bluetooth speakers, Dual automatic signals, Collision crash detection notifications, Certified safety global tags',
    features_fr: 'Haut-parleurs Bluetooth intégrés, Signaux LED automatiques, Détection intelligente de chute, Certifié conforme aux normes',
    tag_ar: 'سلامة أولاً',
    tag_en: 'Safety Choice',
    tag_fr: 'Recommandé',
    image: 'https://images.unsplash.com/photo-1557980313-25c7e19335ef?auto=format&fit=crop&w=800&q=80',
    additional_images: [
      'https://images.unsplash.com/photo-1596701062951-8f68cf4c72ca?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80'
    ],
    price: 195,
    stock: 15,
    category: 'bikes',
    rating_sum: 5,
    rating_count: 1,
    is_featured: false
  },
  {
    id: 'prod-digital-1',
    name_ar: 'دليل صيانة المحركات الرياضية ومشاكل الاحتراق 📖',
    name_en: 'Sport Engine Maintenance & Troubleshooting Manual 📖',
    name_fr: 'Manuel d\'entretien des moteurs sportifs et dépannage 📖',
    description_ar: 'الكتيب الذهبي الشامل المكتوب باللغة العربية لشرح صيانة محركات الدراجات النارية ثنائية ورباعية الأشواط وحل مشكلات ضغط الوقود والكهرباء بدقة بالمنزل.',
    description_en: 'The comprehensive gold manual explaining 2-stroke and 4-stroke motorcycle engine maintenance, fuel pressure fixes, and electrical system diagnostics at home.',
    description_fr: 'Le guide complet expliquant l\'entretien des moteurs 2 temps et 4 temps, les réparations de pression de carburant et les diagnostics électriques.',
    features_ar: 'ملف PDF جاهز للتحميل فوراً, 150 صفحة مدعومة بالصور الملونة, نصائح صيانة سريعة, فصول صيانة البواجي والكربراتير',
    features_en: 'Instant PDF download format, 150 pages with high-res illustrations, quick troubleshooting checklists, spark plug & carburetor chapters',
    features_fr: 'Téléchargement PDF immédiat, 150 pages illustrées, fiches de diagnostic rapide, chapitres sur bougies et carburateur',
    tag_ar: 'رقمي - كتاب إلكتروني',
    tag_en: 'Digital - E-Book',
    tag_fr: 'Numérique - Ebook',
    image: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=800&q=80',
    price: 49,
    stock: 9999,
    category: 'digital',
    rating_sum: 45,
    rating_count: 9,
    is_featured: true,
    is_digital: true,
    digital_file_url: 'https://ais-dev-zmeszmhy2b5uzjix2firep-568273887747.europe-west1.run.app/downloads/Ryvo_Engine_Manual_v2.0.pdf',
    digital_delivery_text: 'شكراً لشرائك الكتيب الذهبي للصيانة! تم إرسال رابط التحميل الخاص بك إلى بريدك، كما يمكنك الضغط على زر التحميل في صفحة حسابك لتنزيل دليل صيانة المحركات فوراً بصيغة PDF.'
  },
  {
    id: 'prod-digital-2',
    name_ar: 'دورة القيادة الاحترافية للدراجات النارية في الظروف القاسية 🎥',
    name_en: 'Pro Motorcycle Riding Masterclass - Extreme Conditions 🎥',
    name_fr: 'Masterclass de conduite de moto pro - Conditions extrêmes 🎥',
    description_ar: 'دورة فيديو مسجلة مع بطل سباق الراليات الدولي لشرح التوازن والقيادة على الرمال والمطر، وتجنب الانزلاقات ومناورات الطوارئ للدراجات النارية الرياضية والكروز.',
    description_en: 'A step-by-step recorded video course with an international rally champion covering cornering balance on sand & wet asphalt, slide recovery, and emergency safety maneuvers.',
    description_fr: 'Un cours vidéo complet avec un champion international de rallye couvrant l\'équilibre sur sable et asphalte mouillé, le contrôle de dérapage.',
    features_ar: 'فيديو عالي الدقة HD 1080p, 12 درساً مفصلاً, شهادة إكمال معتمدة من رايفو, إمكانية تشغيل مدى الحياة على أي جهاز',
    features_en: 'Full HD 1080p stream & download, 12 comprehensive chapters, certified completion tag from Ryvo, lifetime access across any mobile/PC device',
    features_fr: 'Vidéo Full HD 1080p, 12 chapitres détaillés, certificat de complétion Ryvo, accès à vie sur tout appareil',
    tag_ar: 'رقمي - دورة فيديو',
    tag_en: 'Digital - Video Course',
    tag_fr: 'Numérique - Cours Vidéo',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
    price: 199,
    stock: 9999,
    category: 'digital',
    rating_sum: 20,
    rating_count: 4,
    is_featured: true,
    is_digital: true,
    digital_file_url: 'https://ais-dev-zmeszmhy2b5uzjix2firep-568273887747.europe-west1.run.app/downloads/Ryvo_Riding_Masterclass.zip',
    digital_delivery_text: 'يسعدنا انضمامك للدورة! رابط مشاهدة وتحميل الدروس المسجلة والملحقات متاح الآن في لوحة حسابك، ونتمنى لك رحلة تعليمية ومغامرة قيادة شيقة وآمنة.'
  }
];
